
package br.com.fiap.exemplo.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWeb", targetNamespace = "http://ws.exemplo.fiap.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWeb {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ola", targetNamespace = "http://ws.exemplo.fiap.com.br/", className = "br.com.fiap.exemplo.ws.client.Ola")
    @ResponseWrapper(localName = "olaResponse", targetNamespace = "http://ws.exemplo.fiap.com.br/", className = "br.com.fiap.exemplo.ws.client.OlaResponse")
    @Action(input = "http://ws.exemplo.fiap.com.br/HelloWeb/olaRequest", output = "http://ws.exemplo.fiap.com.br/HelloWeb/olaResponse")
    public String ola(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
